package wordcount.io;

public enum Errors {

    READ_TEXT_ERROR,
    TEXT_INPUT_IS_NULL,
    TEXT_SHOULD_NOT_BE_EMPTY,
    ERRORS_ACCESSING_RESOURCE_STOPWORD_READER,
    ERRORS_IN_STOPWORD_READER,
    ERRORS_ACCESSING_RESOURCE_TEXT_SERVICE_FACADE,
    FILE_CANNOT_BE_NULL_TEXT_SERVICE_FACADE,

}
